Vagrant.configure(2) do |config|
  config.vm.box = "box-cutter/centos70"
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 8000, host: 8000
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 1
  end
end
